### ISSUE TITLE
Apps - is Substreamer open source?

### ISSUE THREAD

**Issue by 4oo4** [airsonic/airsonic-docs#43]
Just curious if anyone knew where the source code for this was, since their website (substreamerapp.com) seems to be down? It's a great app but if we can't find source code, it should be marked it as non-free in `apps/docs.md`.

**Comment by jooola** [comment]
Yes I think we should write an email to the dev to see what's going on.

gaven.henry@redsector.com.sg

If no answer I will remove his app from the documentation

**Comment by 4oo4** [comment]
I just looked at a [version](https://web.archive.org/web/20170215235029/http://substreamerapp.com:80/) from the website from February 2017 and there was no link to the source code. Also found his [github](https://github.com/ghenry22) and there's no repo for it there either.

@ghenry22, if you're out there, let us know where things are at! Really love this app and would be sad if it's going unmaintained.

**Comment by ghenry22** [comment]
Hi all,

Substreamer is still actively maintained, the website is being refreshed and will be back shortly as well.

I have actually just started work on a big refresh to the UI and experimenting with adding some new functionality for audio control.

**Comment by ghenry22** [comment]
Oh forgot to mention, it isn’t open source but it is free

**Comment by 4oo4** [comment]
@ghenry22 Thanks for the clarification. I can't tell you what to do with your code, but it would be really nice if this was open sourced some day, I would love to participate in its development, I'm guessing there are others who would too.

@jooola I think maybe I confused the free/non-free listing of Airsonic apps, was that referring to no-cost or open source?

Cheers

**Comment by ghenry22** [comment]
@4oo4 a public issue tracker is a good idea. I’ll setup a project with issues enabled on github and link it off the new website as well.  Always happy to receive feedback and fix things, add features etc.

I don’t have any intention to open source it while I am actively maintaining it, if I ever hit a point where I don’t have the time or inclination to maintain it any more I would make make it open source at that time though so someone else could take over

**Comment by ghenry22** [comment]
@jooola Substreamer is still actively maintained and available, I just haven't had time to do anything with the website unfortunately.  I will resolve that in the coming week.  Should have some updates coming out soon as well with various small bug fixes, mostly related to changes with updated OS/Device features.

**Comment by jvoisin** [comment]
The website is still down, but the app is alive, but since we're only linking to appstore/playstore, I guess it's ok.

**Comment by ghenry22** [comment]
@jvoisin yeh I have been meaning to deal with the web site, just life getting in the way...

**Comment by eharris** [comment]
It's really unfortunate that there doesn't seem to be any public documentation or website or anything for Substreamer.  The original website has been dead for more than a year, and nothing has replaced it.  I tried it out a while back and gave up on it because it was buggy and lacked features, and there was no place to report bugs or find documentation or anything.

Just my $0.02, but it doesn't seem very actively maintained if after a year and a half of "new website and bugtracker coming" there's still nothing.  To me that sounds like a dead project, and because it is closed source, that means no one else can contribute or pick up the maintenance and development, which is sad.

**Comment by jooola** [comment]
Substreamer has been removed from the apps list.

**Comment by ghenry22** [comment]
@eharris while there hasn't been a new release of substreamer for some time it generally works quite well for a large number of users and feedback sent through the app stores or email channels is actively responded to and fed into the development backlog.

I have been actively working on a major refresh that should come out soon and at that time I will also publish a new web site to accompany the release.  It would be great if you could leave it on the list for the time being as it helps people find the app.

Alternatively I guess add it back on to the list when the new versions comes out.

**Comment by jooola** [comment]
@ghenry22 Open a new ticket once your website is back and everything is up-to-date. This ticket has been open for way too long and has not been given enough attention from both parts.

**Comment by eharris** [comment]
@ghenry22 I was just looking at client apps again, and it seems that after more than 2 years of you claiming to be working on a new website that will be available "shortly", there is still no working website, no bug tracker, and no new release in over 3 years.  I would again like to encourage you to open source it if you do not have time to maintain it.  Thanks.

**Comment by ghost** [comment]
@ghenry22 Seems to still be the case in 2021. And the app is no longer working for me. Its the nicest looking client for android I can find and I would love help with the development. Seems a shame to let your hard work go to waste by not releasing it or asking for support.

**Comment by ghenry22** [comment]
For those of you who are interested major release just went out to both app stores and new website is up and running.  Took longer than I expected but life sometimes gets in the way :)
https://substreamerapp.com/

**Comment by jmccoy555** [comment]
@ghenry22 exciting news, but on both Android and iPad I'm seeing `111 Could not connect to server`..... where can I open an issue as this is obviously not the right repo?

**Comment by ghenry22** [comment]
@jmccoy555 give the latest version a try, I have fixed a lot of issues with different server variations.  If you still have issues or questions you can hit https://reddit.com/r/substreamer or contact ghenry22.apps@gmail.com
